env:
  - CI=false
  - GENERATE_SOURCEMAP=false
  - GITHUB_TOKEN=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
before:
  hooks:
    - go mod tidy
    - sh -c "cd assets && rm -rf build && yarn install --network-timeout 1000000 && yarn run build && cd ../ && zip -r - assets/build >assets.zip"
builds:
  -
    env:
      - CGO_ENABLED=0
      - GITHUB_TOKEN=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

    binary: cloudreve

    ldflags:
      - -X 'github.com/Transwarpcom/Cloudreve/v3/pkg/conf.BackendVersion={{.Tag}}' -X 'github.com/Transwarpcom/Cloudreve/v3/pkg/conf.LastCommit={{.ShortCommit}}'

    goos:
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 5
      - 6
      - 7

    ignore:
      - goos: windows
        goarm: 5
      - goos: windows
        goarm: 6
      - goos: windows
        goarm: 7

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      cloudreve_{{.Tag}}_{{- .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: true
  prerelease: auto
  target_commitish: '{{ .Commit }}'
  name_template: "{{.Version}}"

